#!/usr/bin/env bash
# Runs the cram testing tool https://pypi.org/project/cram/ with $PYTHONPATH set

# Ensure this script is run from the repository root
cd "$(git rev-parse --show-toplevel)" || exit

PYTHONPATH="$PYTHONPATH:$(pwd)" cram -E "$@"
